slack:
  api_token: <%= ENV["SLACK_API_TOKEN"] || '' %>

facebook:
  page_access_token: EAAe2YWdmM9oBAM6w65S9G8JUbRDKKISuksL0UJcpxFsVLTLTZAFJgH8I1Ma5lAVZCMVrxFPQV9PSylLvS746GifUdBgWUGksqedoHWkfrL9qdBYoD4bsw7GQSfTPtnVOPzCqVe11qx7ZBcHkxyZBTcAE3WZCgcQIKcv82LU2eBnoM6OWCwr7ZB
  verify_token: a_really_long_and_random_token

root:
  app_id: cee02e5c-df16-11e7-933f-4351e14577f3 #<%= ENV["ROOT_APP_ID"] || ENV["ROOT_API_ID"] || '' %>
  app_secret: b7Uc3CW-jU5lZfU_4AZ3zs3l4l9S-oFO #<%= ENV["ROOT_APP_SECRET"] || '' %>
